-- stylua: ignore
local palette = {
  black   = '#1c2128',
  white   = '#cdd9e5',

  gray0   = '#cdd9e5',
  gray1   = '#adbac7',
  gray2   = '#909dab',
  gray3   = '#768390',
  gray4   = '#636e7b',
  gray5   = '#545d68',
  gray6   = '#444c56',
  gray7   = '#373e47',
  gray8   = '#2d333b',
  gray9   = '#22272e',

  blue0   = '#c6e6ff',
  blue1   = '#96d0ff',
  blue2   = '#6cb6ff',
  blue3   = '#539bf5',
  blue4   = '#4184e4',
  blue5   = '#316dca',
  blue6   = '#255ab2',
  blue7   = '#1b4b91',
  blue8   = '#143d79',
  blue9   = '#0f2d5c',

  green0  = '#b4f1b4',
  green1  = '#8ddb8c',
  green2  = '#6bc46d',
  green3  = '#57ab5a',
  green4  = '#46954a',
  green5  = '#347d39',
  green6  = '#2b6a30',
  green7  = '#245829',
  green8  = '#1b4721',
  green9  = '#113417',

  teal0   = "#f7ffff",
  teal1   = "#dcfffd",
  teal2   = "#ccfffc",
  teal3   = "#a6fffa",
  teal4   = "#73fff7",
  teal5   = "#05f7f4",
  teal6   = "#2de3da",
  teal7   = "#00bdb6",
  teal8   = "#10a39e",
  teal9   = "#008577",

  yellow0 = '#fbe090',
  yellow1 = '#eac55f',
  yellow2 = '#daaa3f',
  yellow3 = '#c69026',
  yellow4 = '#ae7c14',
  yellow5 = '#966600',
  yellow6 = '#805400',
  yellow7 = '#6c4400',
  yellow8 = '#593600',
  yellow9 = '#452700',

  orange0 = '#ffddb0',
  orange1 = '#ffbc6f',
  orange2 = '#f69d50',
  orange3 = '#e0823d',
  orange4 = '#cc6b2c',
  orange5 = '#ae5622',
  orange6 = '#94471b',
  orange7 = '#7f3913',
  orange8 = '#682d0f',
  orange9 = '#4d210c',

  red0    = '#ffd8d3',
  red1    = '#ffb8b0',
  red2    = '#ff938a',
  red3    = '#f47067',
  red4    = '#e5534b',
  red5    = '#c93c37',
  red6    = '#ad2e2c',
  red7    = '#922323',
  red8    = '#78191b',
  red9    = '#5d0f12',

  purple0 = '#eedcff',
  purple1 = '#dcbdfb',
  purple2 = '#dcbdfb',
  purple3 = '#b083f0',
  purple4 = '#986ee2',
  purple5 = '#8256d0',
  purple6 = '#6b44bc',
  purple7 = '#5936a2',
  purple8 = '#472c82',
  purple9 = '#352160',

  pink0   = '#ffd7eb',
  pink1   = '#ffb3d8',
  pink2   = '#fc8dc7',
  pink3   = '#e275ad',
  pink4   = '#c96198',
  pink5   = '#ae4c82',
  pink6   = '#983b6e',
  pink7   = '#7e325a',
  pink8   = '#69264a',
  pink9   = '#551639',

  coral0  = '#ffdacf',
  coral1  = '#ffb9a5',
  coral2  = '#f79981',
  coral3  = '#ec775c',
  coral4  = '#de5b41',
  coral5  = '#c2442d',
  coral6  = '#a93524',
  coral7  = '#8d291b',
  coral8  = '#771d13',
  coral9  = '#5d1008',
}

local colors = {}

if vim.o.background == 'dark' then
  colors = {
    error_foreground = palette.red4,
    warning_foreground = palette.yellow3,
    info_foreground = palette.blue3,
    hint_foreground = palette.gray3,

    syntax = {
      comment = palette.gray3,
      number = palette.coral5,
      constant = palette.blue2,
      func = palette.purple2,
      character = palette.green1,
      string = palette.blue1,
      identifier = palette.blue2,
      keyword = palette.red3,
      storage = palette.red3,
      tag = palette.gray1,
      debug = palette.gray3,
      delimiter = palette.gray1,
      operator = palette.gray1,
      type = palette.orange2,
      todo = palette.green2,
      include = palette.red3,
      exception = palette.teal5,
      preprocessor = palette.gray1,
      macro = palette.yellow1,
    },

    editor = {
      background = palette.gray9,
      bracket_match_background = palette.green3,
      bufferline = {
        active_border = palette.coral3,
        foreground = palette.gray5,
        active_foreground = palette.gray1,
      },
      colorcolumn = palette.gray8,
      diff = {
        inserted_line_background = palette.green7,
        inserted_text_background = palette.green5,
        removed_line_background = palette.red7,
        removed_text_background = palette.red5,
        old_file = palette.coral5,
        new_file = palette.green5,
        file = palette.blue5,
      },
      find_match = { background = palette.yellow5, current = palette.yellow2 },
      fold_background = palette.gray4,
      foreground = palette.gray1,
      git = {
        added_resource_foreground = palette.green4,
        modified_resource_foreground = palette.yellow4,
        deleted_resource_foreground = palette.red4,
        untracked_resource_foreground = palette.green4,
        ignored_resource_foreground = palette.gray5,
        conflicting_resource_foreground = palette.orange4,
        submodule_resource_foreground = palette.gray3,
        blame_text_foreground = palette.gray5,
      },
      indent_guide = {
        background = palette.gray7,
        active_background = palette.gray5,
      },
      line_highlight_background = palette.gray8,
      line_number = {
        foreground = palette.gray4,
        active_foreground = palette.gray1,
      },
      popup = {
        foreground = palette.gray1,
        background = palette.gray8,
        highlight_blue = '#004b72',
        highlight_gray = '#343b41',
      },
      selection = '#264f78',
      split_border = palette.gray6,
      title_foreground = palette.blue2,
      whitespace = palette.gray5,
    },
  }
else
  assert(vim.o.background == 'light', 'Invalid theme ' .. vim.o.background)
  -- TODO: create light theme
  colors = {
    error_foreground = '#cb2431',
    warning_foreground = '#f9c513',
    info_foreground = '#005cc5',
    hint_foreground = palette.gray5,

    syntax = {
      comment = '#6a737d',
      number = palette.coral5,
      constant = '#005cc5',
      func = '#6f42c1',
      character = '#22863a',
      string = '#032f62',
      identifier = '#005cc5',
      keyword = '#d73a49',
      storage = '#d73a49',
      tag = '#22863a',
      debug = '#586069',
      delimiter = '#586069',
      operator = '#24292e',
      type = '#e36209',
      todo = '#22863a',
      include = '#d73a49',
      exception = palette.teal5,
      preprocessor = '#24292e',
      macro = '#ffdf5d',
    },

    editor = {
      background = '#ffffff',
      bracket_match_background = palette.green3,
      bufferline = {
        active_border = palette.coral3,
        foreground = palette.gray1,
        active_foreground = palette.gray5,
      },
      colorcolumn = '#f6f8fa',
      diff = {
        inserted_line_background = palette.green7,
        inserted_text_background = palette.green5,
        removed_line_background = palette.red7,
        removed_text_background = palette.red5,
        old_file = palette.coral5,
        new_file = palette.green5,
        file = palette.blue5,
      },
      find_match = { background = '#ffdf5d', current = palette.yellow2 },
      fold_background = palette.gray4,
      foreground = '#24292e',
      git = {
        added_resource_foreground = palette.green4,
        modified_resource_foreground = palette.yellow4,
        deleted_resource_foreground = palette.red4,
        untracked_resource_foreground = palette.green4,
        ignored_resource_foreground = palette.gray5,
        conflicting_resource_foreground = palette.orange4,
        submodule_resource_foreground = palette.gray3,
        blame_text_foreground = palette.gray5,
      },
      indent_guide = {
        background = '#f6f8fa',
        active_background = '#e1e4e8',
      },
      line_highlight_background = '#f6f8fa',
      line_number = {
        foreground = palette.gray1,
        active_foreground = palette.gray4,
      },
      popup = {
        foreground = '#24292e',
        background = '#e1e4e8',
        highlight_blue = '#accbff',
        highlight_gray = '#d1d5da',
      },
      selection = palette.blue0,
      split_border = palette.gray2,
      title_foreground = palette.blue2,
      whitespace = '#d1d5da',
    },
  }
end

-- Shared colors
colors.none = 'None'
colors.editor.cursor = {
  background = '#00ff00',
  active_background = '#ff0000',
}
colors.yank = '#2ecc71'

return vim.tbl_extend('force', colors, palette)
